package com.fyp.hotel.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "payment_method")
@RequiredArgsConstructor // generate constructor with all final fields as arguments
public class PaymentMethod {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //identity means that the id will be generated by the database and it will not be in sequence and it will be unique
    @Column(name = "payment_method_id", nullable = false, unique = true)
    private Long paymentMethodId;

    @Column(name = "payment_method_name", nullable = false, length = 50)
    private String paymentMethodName;

//    @JsonIgnore // JSON ignore is used to ignore the JSON serialization and deserialization of a field
//    @JsonBackReference //json back reference doesn't allow to serialize the child object
    @OneToMany(mappedBy = "paymentMethod", cascade = CascadeType.ALL)
    private List<Booking> bookings = new ArrayList<>();

    @Override
    public String toString() {
        return "PaymentMethod{" +
                "paymentMethodId=" + paymentMethodId +
                ", paymentMethodName='" + paymentMethodName + '\'' +
                '}';
    }
}
