package com.fyp.hotel.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "payment_method")
@RequiredArgsConstructor // generate constructor with all final fields as arguments
public class PaymentMethod {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //identity means that the id will be generated by the database and it will not be in sequence and it will be unique
    @Column(name = "payment_method_id", nullable = false, unique = true)
    private Long paymentMethodId;

    @Column(name = "payment_method_name", nullable = false, length = 50)
    private String paymentMethodName;

    @OneToMany(mappedBy = "paymentMethod", cascade = CascadeType.ALL)
    private List<Booking> bookings = new ArrayList<>();

    @Override
    public String toString() {
        return "PaymentMethod{" +
                "paymentMethodId=" + paymentMethodId +
                ", paymentMethodName='" + paymentMethodName + '\'' +
                '}';
    }
}
